### PR TITLE
Chore - Styling

### PR DESCRIPTION
**Pull request by emtalen**
### User Story
```
As a development team
We do not always see the details straight away
So we need to go back and fix them
```
## Changes proposed in this pull request:
* Spinner when loading authentication response
* Back button to close pending requests 

## What I have learned working on this feature:
* It is very hard to take a screen shot of 

## Packages/Gems added
- React Spinners

## Screenshots (Client)
Screenshot 2020-04-24 at 14 39 49

### CODE REVIEW

**Review by johanbounce — APPROVED** [review]
Absolutely stunning! I approve

**Comment by johanbounce** [comment]
I will merge this after you have accepted Mr.Pungråttzon to this community

**Review by pgaunitz — APPROVED** [review]
LGTM :racehorse:

**Review by kfrostare — APPROVED** [review]
Looks good :)

**Pull request merged**
